version: '3.3'
services:
  web:
    image: tubes-1:latest
    volumes:
      - ./src/app:/var/www/app
      - ./src/public:/var/www/html
    ports:
      - 8008:80
    depends_on:
      - db
    build:
      dockerfile: Dockerfile
    env_file:
      - .env

  db:
    image: postgres:latest
    restart: always
    volumes:
      - "./db:/var/lib/postgresql/data"
      - "./db_init/entrypoint.sh:/docker-entrypoint-initdb.d/0.sh"
      - "./db_init/schema.sql:/docker-entrypoint-initdb.d/1.sql"
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_DB: wetube

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8888:8080"
    depends_on:
      - db